// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sftp.proto

package com.proto.go.sftp;

public interface CopyLocalToRemoteResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sftp.CopyLocalToRemoteResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string result = 1;</code>
   * @return The result.
   */
  java.lang.String getResult();
  /**
   * <code>string result = 1;</code>
   * @return The bytes for result.
   */
  com.google.protobuf.ByteString
      getResultBytes();
}
