// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sftp.proto

package com.proto.go.sftp;

public interface CopyFromRemoteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sftp.CopyFromRemoteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.sftp.Sftp sftp = 1;</code>
   */
  boolean hasSftp();
  /**
   * <code>.sftp.Sftp sftp = 1;</code>
   */
  com.proto.go.sftp.Sftp getSftp();
  /**
   * <code>.sftp.Sftp sftp = 1;</code>
   */
  com.proto.go.sftp.SftpOrBuilder getSftpOrBuilder();
}
