// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sftp.proto

package com.proto.go.sftp;

/**
 * Protobuf type {@code sftp.GetDirRequest}
 */
public  final class GetDirRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:sftp.GetDirRequest)
    GetDirRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetDirRequest.newBuilder() to construct.
  private GetDirRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetDirRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetDirRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetDirRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.proto.go.sftp.List.Builder subBuilder = null;
            if (list_ != null) {
              subBuilder = list_.toBuilder();
            }
            list_ = input.readMessage(com.proto.go.sftp.List.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(list_);
              list_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.proto.go.sftp.SftpOuterClass.internal_static_sftp_GetDirRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.proto.go.sftp.SftpOuterClass.internal_static_sftp_GetDirRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.proto.go.sftp.GetDirRequest.class, com.proto.go.sftp.GetDirRequest.Builder.class);
  }

  public static final int LIST_FIELD_NUMBER = 1;
  private com.proto.go.sftp.List list_;
  /**
   * <code>.sftp.List list = 1;</code>
   * @return Whether the list field is set.
   */
  public boolean hasList() {
    return list_ != null;
  }
  /**
   * <code>.sftp.List list = 1;</code>
   * @return The list.
   */
  public com.proto.go.sftp.List getList() {
    return list_ == null ? com.proto.go.sftp.List.getDefaultInstance() : list_;
  }
  /**
   * <code>.sftp.List list = 1;</code>
   */
  public com.proto.go.sftp.ListOrBuilder getListOrBuilder() {
    return getList();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (list_ != null) {
      output.writeMessage(1, getList());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (list_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getList());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.proto.go.sftp.GetDirRequest)) {
      return super.equals(obj);
    }
    com.proto.go.sftp.GetDirRequest other = (com.proto.go.sftp.GetDirRequest) obj;

    if (hasList() != other.hasList()) return false;
    if (hasList()) {
      if (!getList()
          .equals(other.getList())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasList()) {
      hash = (37 * hash) + LIST_FIELD_NUMBER;
      hash = (53 * hash) + getList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.proto.go.sftp.GetDirRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.proto.go.sftp.GetDirRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.proto.go.sftp.GetDirRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.proto.go.sftp.GetDirRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.proto.go.sftp.GetDirRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.proto.go.sftp.GetDirRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.proto.go.sftp.GetDirRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.proto.go.sftp.GetDirRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.proto.go.sftp.GetDirRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.proto.go.sftp.GetDirRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.proto.go.sftp.GetDirRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.proto.go.sftp.GetDirRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.proto.go.sftp.GetDirRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code sftp.GetDirRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:sftp.GetDirRequest)
      com.proto.go.sftp.GetDirRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.proto.go.sftp.SftpOuterClass.internal_static_sftp_GetDirRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.proto.go.sftp.SftpOuterClass.internal_static_sftp_GetDirRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.proto.go.sftp.GetDirRequest.class, com.proto.go.sftp.GetDirRequest.Builder.class);
    }

    // Construct using com.proto.go.sftp.GetDirRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (listBuilder_ == null) {
        list_ = null;
      } else {
        list_ = null;
        listBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.proto.go.sftp.SftpOuterClass.internal_static_sftp_GetDirRequest_descriptor;
    }

    @java.lang.Override
    public com.proto.go.sftp.GetDirRequest getDefaultInstanceForType() {
      return com.proto.go.sftp.GetDirRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.proto.go.sftp.GetDirRequest build() {
      com.proto.go.sftp.GetDirRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.proto.go.sftp.GetDirRequest buildPartial() {
      com.proto.go.sftp.GetDirRequest result = new com.proto.go.sftp.GetDirRequest(this);
      if (listBuilder_ == null) {
        result.list_ = list_;
      } else {
        result.list_ = listBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.proto.go.sftp.GetDirRequest) {
        return mergeFrom((com.proto.go.sftp.GetDirRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.proto.go.sftp.GetDirRequest other) {
      if (other == com.proto.go.sftp.GetDirRequest.getDefaultInstance()) return this;
      if (other.hasList()) {
        mergeList(other.getList());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.proto.go.sftp.GetDirRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.proto.go.sftp.GetDirRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.proto.go.sftp.List list_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.proto.go.sftp.List, com.proto.go.sftp.List.Builder, com.proto.go.sftp.ListOrBuilder> listBuilder_;
    /**
     * <code>.sftp.List list = 1;</code>
     * @return Whether the list field is set.
     */
    public boolean hasList() {
      return listBuilder_ != null || list_ != null;
    }
    /**
     * <code>.sftp.List list = 1;</code>
     * @return The list.
     */
    public com.proto.go.sftp.List getList() {
      if (listBuilder_ == null) {
        return list_ == null ? com.proto.go.sftp.List.getDefaultInstance() : list_;
      } else {
        return listBuilder_.getMessage();
      }
    }
    /**
     * <code>.sftp.List list = 1;</code>
     */
    public Builder setList(com.proto.go.sftp.List value) {
      if (listBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        list_ = value;
        onChanged();
      } else {
        listBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.sftp.List list = 1;</code>
     */
    public Builder setList(
        com.proto.go.sftp.List.Builder builderForValue) {
      if (listBuilder_ == null) {
        list_ = builderForValue.build();
        onChanged();
      } else {
        listBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.sftp.List list = 1;</code>
     */
    public Builder mergeList(com.proto.go.sftp.List value) {
      if (listBuilder_ == null) {
        if (list_ != null) {
          list_ =
            com.proto.go.sftp.List.newBuilder(list_).mergeFrom(value).buildPartial();
        } else {
          list_ = value;
        }
        onChanged();
      } else {
        listBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.sftp.List list = 1;</code>
     */
    public Builder clearList() {
      if (listBuilder_ == null) {
        list_ = null;
        onChanged();
      } else {
        list_ = null;
        listBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.sftp.List list = 1;</code>
     */
    public com.proto.go.sftp.List.Builder getListBuilder() {
      
      onChanged();
      return getListFieldBuilder().getBuilder();
    }
    /**
     * <code>.sftp.List list = 1;</code>
     */
    public com.proto.go.sftp.ListOrBuilder getListOrBuilder() {
      if (listBuilder_ != null) {
        return listBuilder_.getMessageOrBuilder();
      } else {
        return list_ == null ?
            com.proto.go.sftp.List.getDefaultInstance() : list_;
      }
    }
    /**
     * <code>.sftp.List list = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.proto.go.sftp.List, com.proto.go.sftp.List.Builder, com.proto.go.sftp.ListOrBuilder> 
        getListFieldBuilder() {
      if (listBuilder_ == null) {
        listBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.proto.go.sftp.List, com.proto.go.sftp.List.Builder, com.proto.go.sftp.ListOrBuilder>(
                getList(),
                getParentForChildren(),
                isClean());
        list_ = null;
      }
      return listBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:sftp.GetDirRequest)
  }

  // @@protoc_insertion_point(class_scope:sftp.GetDirRequest)
  private static final com.proto.go.sftp.GetDirRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.proto.go.sftp.GetDirRequest();
  }

  public static com.proto.go.sftp.GetDirRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetDirRequest>
      PARSER = new com.google.protobuf.AbstractParser<GetDirRequest>() {
    @java.lang.Override
    public GetDirRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetDirRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetDirRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetDirRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.proto.go.sftp.GetDirRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

