pipeline {
    agent {
        docker {
    		args '-v /root/.m2:/root/.m2'
    		image 'maven:3-alpine'
        }
    }
    stages {
        stage('Build') { 
            steps {
                sh 'mvn -B -DskipTests --pl transfers clean install' 
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'agave-transfers/transfers-api/target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') { 
            steps {
                sh './jenkins/scripts/deliver.sh' 
            }
        }
    }
}