// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sftp.proto

package sftpproto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Sftp struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	PassWord             string   `protobuf:"bytes,2,opt,name=passWord,proto3" json:"passWord,omitempty"`
	SystemId             string   `protobuf:"bytes,3,opt,name=systemId,proto3" json:"systemId,omitempty"`
	HostKey              string   `protobuf:"bytes,4,opt,name=hostKey,proto3" json:"hostKey,omitempty"`
	FileName             string   `protobuf:"bytes,5,opt,name=fileName,proto3" json:"fileName,omitempty"`
	FileSize             int64    `protobuf:"varint,6,opt,name=fileSize,proto3" json:"fileSize,omitempty"`
	HostPort             string   `protobuf:"bytes,7,opt,name=hostPort,proto3" json:"hostPort,omitempty"`
	ClientKey            string   `protobuf:"bytes,8,opt,name=clientKey,proto3" json:"clientKey,omitempty"`
	BufferSize           int64    `protobuf:"varint,9,opt,name=bufferSize,proto3" json:"bufferSize,omitempty"`
	Type                 string   `protobuf:"bytes,10,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sftp) Reset()         { *m = Sftp{} }
func (m *Sftp) String() string { return proto.CompactTextString(m) }
func (*Sftp) ProtoMessage()    {}
func (*Sftp) Descriptor() ([]byte, []int) {
	return fileDescriptor_78fc9c5a618b7cda, []int{0}
}

func (m *Sftp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sftp.Unmarshal(m, b)
}
func (m *Sftp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sftp.Marshal(b, m, deterministic)
}
func (m *Sftp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sftp.Merge(m, src)
}
func (m *Sftp) XXX_Size() int {
	return xxx_messageInfo_Sftp.Size(m)
}
func (m *Sftp) XXX_DiscardUnknown() {
	xxx_messageInfo_Sftp.DiscardUnknown(m)
}

var xxx_messageInfo_Sftp proto.InternalMessageInfo

func (m *Sftp) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Sftp) GetPassWord() string {
	if m != nil {
		return m.PassWord
	}
	return ""
}

func (m *Sftp) GetSystemId() string {
	if m != nil {
		return m.SystemId
	}
	return ""
}

func (m *Sftp) GetHostKey() string {
	if m != nil {
		return m.HostKey
	}
	return ""
}

func (m *Sftp) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *Sftp) GetFileSize() int64 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

func (m *Sftp) GetHostPort() string {
	if m != nil {
		return m.HostPort
	}
	return ""
}

func (m *Sftp) GetClientKey() string {
	if m != nil {
		return m.ClientKey
	}
	return ""
}

func (m *Sftp) GetBufferSize() int64 {
	if m != nil {
		return m.BufferSize
	}
	return 0
}

func (m *Sftp) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type SrvPutRequest struct {
	SrceSftp             *Sftp    `protobuf:"bytes,1,opt,name=srceSftp,proto3" json:"srceSftp,omitempty"`
	DestSftp             *Sftp    `protobuf:"bytes,2,opt,name=destSftp,proto3" json:"destSftp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SrvPutRequest) Reset()         { *m = SrvPutRequest{} }
func (m *SrvPutRequest) String() string { return proto.CompactTextString(m) }
func (*SrvPutRequest) ProtoMessage()    {}
func (*SrvPutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_78fc9c5a618b7cda, []int{1}
}

func (m *SrvPutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SrvPutRequest.Unmarshal(m, b)
}
func (m *SrvPutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SrvPutRequest.Marshal(b, m, deterministic)
}
func (m *SrvPutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SrvPutRequest.Merge(m, src)
}
func (m *SrvPutRequest) XXX_Size() int {
	return xxx_messageInfo_SrvPutRequest.Size(m)
}
func (m *SrvPutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SrvPutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SrvPutRequest proto.InternalMessageInfo

func (m *SrvPutRequest) GetSrceSftp() *Sftp {
	if m != nil {
		return m.SrceSftp
	}
	return nil
}

func (m *SrvPutRequest) GetDestSftp() *Sftp {
	if m != nil {
		return m.DestSftp
	}
	return nil
}

type SrvPutResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SrvPutResponse) Reset()         { *m = SrvPutResponse{} }
func (m *SrvPutResponse) String() string { return proto.CompactTextString(m) }
func (*SrvPutResponse) ProtoMessage()    {}
func (*SrvPutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_78fc9c5a618b7cda, []int{2}
}

func (m *SrvPutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SrvPutResponse.Unmarshal(m, b)
}
func (m *SrvPutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SrvPutResponse.Marshal(b, m, deterministic)
}
func (m *SrvPutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SrvPutResponse.Merge(m, src)
}
func (m *SrvPutResponse) XXX_Size() int {
	return xxx_messageInfo_SrvPutResponse.Size(m)
}
func (m *SrvPutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SrvPutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SrvPutResponse proto.InternalMessageInfo

func (m *SrvPutResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type SrvGetRequest struct {
	SrceSftp             *Sftp    `protobuf:"bytes,1,opt,name=srceSftp,proto3" json:"srceSftp,omitempty"`
	DestSftp             *Sftp    `protobuf:"bytes,2,opt,name=destSftp,proto3" json:"destSftp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SrvGetRequest) Reset()         { *m = SrvGetRequest{} }
func (m *SrvGetRequest) String() string { return proto.CompactTextString(m) }
func (*SrvGetRequest) ProtoMessage()    {}
func (*SrvGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_78fc9c5a618b7cda, []int{3}
}

func (m *SrvGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SrvGetRequest.Unmarshal(m, b)
}
func (m *SrvGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SrvGetRequest.Marshal(b, m, deterministic)
}
func (m *SrvGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SrvGetRequest.Merge(m, src)
}
func (m *SrvGetRequest) XXX_Size() int {
	return xxx_messageInfo_SrvGetRequest.Size(m)
}
func (m *SrvGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SrvGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SrvGetRequest proto.InternalMessageInfo

func (m *SrvGetRequest) GetSrceSftp() *Sftp {
	if m != nil {
		return m.SrceSftp
	}
	return nil
}

func (m *SrvGetRequest) GetDestSftp() *Sftp {
	if m != nil {
		return m.DestSftp
	}
	return nil
}

type SrvGetResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SrvGetResponse) Reset()         { *m = SrvGetResponse{} }
func (m *SrvGetResponse) String() string { return proto.CompactTextString(m) }
func (*SrvGetResponse) ProtoMessage()    {}
func (*SrvGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_78fc9c5a618b7cda, []int{4}
}

func (m *SrvGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SrvGetResponse.Unmarshal(m, b)
}
func (m *SrvGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SrvGetResponse.Marshal(b, m, deterministic)
}
func (m *SrvGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SrvGetResponse.Merge(m, src)
}
func (m *SrvGetResponse) XXX_Size() int {
	return xxx_messageInfo_SrvGetResponse.Size(m)
}
func (m *SrvGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SrvGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SrvGetResponse proto.InternalMessageInfo

func (m *SrvGetResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*Sftp)(nil), "sftpproto.Sftp")
	proto.RegisterType((*SrvPutRequest)(nil), "sftpproto.SrvPutRequest")
	proto.RegisterType((*SrvPutResponse)(nil), "sftpproto.SrvPutResponse")
	proto.RegisterType((*SrvGetRequest)(nil), "sftpproto.SrvGetRequest")
	proto.RegisterType((*SrvGetResponse)(nil), "sftpproto.SrvGetResponse")
}

func init() { proto.RegisterFile("sftp.proto", fileDescriptor_78fc9c5a618b7cda) }

var fileDescriptor_78fc9c5a618b7cda = []byte{
	// 376 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x53, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x25, 0x49, 0x6d, 0x9b, 0x11, 0x2b, 0xec, 0x41, 0xd6, 0x22, 0x52, 0x0a, 0x42, 0x41, 0xc8,
	0xa1, 0xde, 0x7a, 0xb3, 0x97, 0x22, 0x82, 0x84, 0xf4, 0x20, 0x78, 0x4b, 0xdb, 0x49, 0x0d, 0xa4,
	0xd9, 0x75, 0x77, 0x53, 0x88, 0x57, 0xff, 0x85, 0x47, 0x7f, 0xa9, 0xec, 0x26, 0x9b, 0x06, 0xbf,
	0x8e, 0xde, 0xe6, 0xcd, 0x7b, 0x6f, 0xe6, 0x31, 0x9b, 0x00, 0xc8, 0x44, 0xf1, 0x80, 0x0b, 0xa6,
	0x18, 0xf1, 0x75, 0x6d, 0xca, 0xf1, 0xbb, 0x0b, 0x9d, 0x65, 0xa2, 0x38, 0x19, 0x42, 0xbf, 0x90,
	0x28, 0xf2, 0x78, 0x87, 0xd4, 0x19, 0x39, 0x13, 0x3f, 0x6a, 0xb0, 0xe6, 0x78, 0x2c, 0xe5, 0x23,
	0x13, 0x1b, 0xea, 0x56, 0x9c, 0xc5, 0x9a, 0x93, 0xa5, 0x54, 0xb8, 0xbb, 0xdb, 0x50, 0xaf, 0xe2,
	0x2c, 0x26, 0x14, 0x7a, 0xcf, 0x4c, 0xaa, 0x7b, 0x2c, 0x69, 0xc7, 0x50, 0x16, 0x6a, 0x57, 0x92,
	0x66, 0xf8, 0xa0, 0xb7, 0x1d, 0x55, 0x2e, 0x8b, 0x2d, 0xb7, 0x4c, 0x5f, 0x91, 0x76, 0x47, 0xce,
	0xc4, 0x8b, 0x1a, 0xac, 0x39, 0x3d, 0x22, 0x64, 0x42, 0xd1, 0x5e, 0xe5, 0xb3, 0x98, 0x5c, 0x80,
	0xbf, 0xce, 0x52, 0xcc, 0xcd, 0xbe, 0xbe, 0x21, 0x0f, 0x0d, 0x72, 0x09, 0xb0, 0x2a, 0x92, 0x04,
	0x85, 0x99, 0xeb, 0x9b, 0xb9, 0xad, 0x0e, 0x21, 0xd0, 0x51, 0x25, 0x47, 0x0a, 0xc6, 0x68, 0xea,
	0x71, 0x0a, 0x27, 0x4b, 0xb1, 0x0f, 0x0b, 0x15, 0xe1, 0x4b, 0x81, 0x52, 0x91, 0x6b, 0xe8, 0x4b,
	0xb1, 0x46, 0x7d, 0x30, 0x73, 0xa4, 0xe3, 0xe9, 0x69, 0xd0, 0xdc, 0x32, 0xd0, 0xed, 0xa8, 0x11,
	0x68, 0xf1, 0x06, 0xa5, 0x32, 0x62, 0xf7, 0x17, 0xb1, 0x15, 0x8c, 0x27, 0x30, 0xb0, 0xab, 0x24,
	0x67, 0xb9, 0x44, 0x72, 0x06, 0x5d, 0x81, 0xb2, 0xc8, 0x54, 0xfd, 0x1c, 0x35, 0xaa, 0x43, 0x2d,
	0xf0, 0xdf, 0x42, 0x99, 0x55, 0x7f, 0x87, 0x9a, 0xbe, 0x39, 0xe0, 0x1b, 0x33, 0x66, 0x71, 0x49,
	0x66, 0xe0, 0x2d, 0x50, 0x11, 0xda, 0x9e, 0xdc, 0x8e, 0x3c, 0x3c, 0xff, 0x81, 0xa9, 0x37, 0xcc,
	0xc0, 0x0b, 0x8b, 0x6f, 0xde, 0xc3, 0x1b, 0x7c, 0xf5, 0xb6, 0x4e, 0x36, 0x0f, 0xe1, 0x8a, 0x89,
	0x6d, 0x10, 0x6f, 0xe3, 0x3d, 0xf2, 0x2c, 0x56, 0x09, 0x13, 0xbb, 0x40, 0x89, 0x38, 0x97, 0x09,
	0x8a, 0xea, 0xdb, 0x37, 0xe6, 0xf9, 0xe0, 0x56, 0x4b, 0x74, 0xe0, 0x50, 0x37, 0x43, 0xe7, 0xe9,
	0xf0, 0x4b, 0x7c, 0xb8, 0x7e, 0xc3, 0xae, 0xba, 0xa6, 0x75, 0xf3, 0x19, 0x00, 0x00, 0xff, 0xff,
	0x06, 0x90, 0xb6, 0x29, 0x3e, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SftpRelayClient is the client API for SftpRelay service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SftpRelayClient interface {
	Get(ctx context.Context, in *SrvGetRequest, opts ...grpc.CallOption) (*SrvGetResponse, error)
	Put(ctx context.Context, in *SrvPutRequest, opts ...grpc.CallOption) (*SrvPutResponse, error)
}

type sftpRelayClient struct {
	cc *grpc.ClientConn
}

func NewSftpRelayClient(cc *grpc.ClientConn) SftpRelayClient {
	return &sftpRelayClient{cc}
}

func (c *sftpRelayClient) Get(ctx context.Context, in *SrvGetRequest, opts ...grpc.CallOption) (*SrvGetResponse, error) {
	out := new(SrvGetResponse)
	err := c.cc.Invoke(ctx, "/sftpproto.SftpRelay/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sftpRelayClient) Put(ctx context.Context, in *SrvPutRequest, opts ...grpc.CallOption) (*SrvPutResponse, error) {
	out := new(SrvPutResponse)
	err := c.cc.Invoke(ctx, "/sftpproto.SftpRelay/Put", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SftpRelayServer is the server API for SftpRelay service.
type SftpRelayServer interface {
	Get(context.Context, *SrvGetRequest) (*SrvGetResponse, error)
	Put(context.Context, *SrvPutRequest) (*SrvPutResponse, error)
}

// UnimplementedSftpRelayServer can be embedded to have forward compatible implementations.
type UnimplementedSftpRelayServer struct {
}

func (*UnimplementedSftpRelayServer) Get(ctx context.Context, req *SrvGetRequest) (*SrvGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedSftpRelayServer) Put(ctx context.Context, req *SrvPutRequest) (*SrvPutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Put not implemented")
}

func RegisterSftpRelayServer(s *grpc.Server, srv SftpRelayServer) {
	s.RegisterService(&_SftpRelay_serviceDesc, srv)
}

func _SftpRelay_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SrvGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SftpRelayServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sftpproto.SftpRelay/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SftpRelayServer).Get(ctx, req.(*SrvGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SftpRelay_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SrvPutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SftpRelayServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sftpproto.SftpRelay/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SftpRelayServer).Put(ctx, req.(*SrvPutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SftpRelay_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sftpproto.SftpRelay",
	HandlerType: (*SftpRelayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _SftpRelay_Get_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _SftpRelay_Put_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sftp.proto",
}
