// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sftp.proto

package sftp

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Sftp struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	PassWord             string   `protobuf:"bytes,2,opt,name=passWord,proto3" json:"passWord,omitempty"`
	SystemId             string   `protobuf:"bytes,3,opt,name=systemId,proto3" json:"systemId,omitempty"`
	HostKey              string   `protobuf:"bytes,4,opt,name=hostKey,proto3" json:"hostKey,omitempty"`
	FileName             string   `protobuf:"bytes,5,opt,name=fileName,proto3" json:"fileName,omitempty"`
	HostPort             string   `protobuf:"bytes,6,opt,name=hostPort,proto3" json:"hostPort,omitempty"`
	ClientKey            string   `protobuf:"bytes,7,opt,name=clientKey,proto3" json:"clientKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sftp) Reset()         { *m = Sftp{} }
func (m *Sftp) String() string { return proto.CompactTextString(m) }
func (*Sftp) ProtoMessage()    {}
func (*Sftp) Descriptor() ([]byte, []int) {
	return fileDescriptor_78fc9c5a618b7cda, []int{0}
}

func (m *Sftp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sftp.Unmarshal(m, b)
}
func (m *Sftp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sftp.Marshal(b, m, deterministic)
}
func (m *Sftp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sftp.Merge(m, src)
}
func (m *Sftp) XXX_Size() int {
	return xxx_messageInfo_Sftp.Size(m)
}
func (m *Sftp) XXX_DiscardUnknown() {
	xxx_messageInfo_Sftp.DiscardUnknown(m)
}

var xxx_messageInfo_Sftp proto.InternalMessageInfo

func (m *Sftp) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Sftp) GetPassWord() string {
	if m != nil {
		return m.PassWord
	}
	return ""
}

func (m *Sftp) GetSystemId() string {
	if m != nil {
		return m.SystemId
	}
	return ""
}

func (m *Sftp) GetHostKey() string {
	if m != nil {
		return m.HostKey
	}
	return ""
}

func (m *Sftp) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *Sftp) GetHostPort() string {
	if m != nil {
		return m.HostPort
	}
	return ""
}

func (m *Sftp) GetClientKey() string {
	if m != nil {
		return m.ClientKey
	}
	return ""
}

type CopyLocalToRemoteRequest struct {
	Sftp                 *Sftp    `protobuf:"bytes,1,opt,name=sftp,proto3" json:"sftp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CopyLocalToRemoteRequest) Reset()         { *m = CopyLocalToRemoteRequest{} }
func (m *CopyLocalToRemoteRequest) String() string { return proto.CompactTextString(m) }
func (*CopyLocalToRemoteRequest) ProtoMessage()    {}
func (*CopyLocalToRemoteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_78fc9c5a618b7cda, []int{1}
}

func (m *CopyLocalToRemoteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CopyLocalToRemoteRequest.Unmarshal(m, b)
}
func (m *CopyLocalToRemoteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CopyLocalToRemoteRequest.Marshal(b, m, deterministic)
}
func (m *CopyLocalToRemoteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CopyLocalToRemoteRequest.Merge(m, src)
}
func (m *CopyLocalToRemoteRequest) XXX_Size() int {
	return xxx_messageInfo_CopyLocalToRemoteRequest.Size(m)
}
func (m *CopyLocalToRemoteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CopyLocalToRemoteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CopyLocalToRemoteRequest proto.InternalMessageInfo

func (m *CopyLocalToRemoteRequest) GetSftp() *Sftp {
	if m != nil {
		return m.Sftp
	}
	return nil
}

type CopyLocalToRemoteResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CopyLocalToRemoteResponse) Reset()         { *m = CopyLocalToRemoteResponse{} }
func (m *CopyLocalToRemoteResponse) String() string { return proto.CompactTextString(m) }
func (*CopyLocalToRemoteResponse) ProtoMessage()    {}
func (*CopyLocalToRemoteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_78fc9c5a618b7cda, []int{2}
}

func (m *CopyLocalToRemoteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CopyLocalToRemoteResponse.Unmarshal(m, b)
}
func (m *CopyLocalToRemoteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CopyLocalToRemoteResponse.Marshal(b, m, deterministic)
}
func (m *CopyLocalToRemoteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CopyLocalToRemoteResponse.Merge(m, src)
}
func (m *CopyLocalToRemoteResponse) XXX_Size() int {
	return xxx_messageInfo_CopyLocalToRemoteResponse.Size(m)
}
func (m *CopyLocalToRemoteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CopyLocalToRemoteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CopyLocalToRemoteResponse proto.InternalMessageInfo

func (m *CopyLocalToRemoteResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type CopyFromRemoteRequest struct {
	Sftp                 *Sftp    `protobuf:"bytes,1,opt,name=sftp,proto3" json:"sftp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CopyFromRemoteRequest) Reset()         { *m = CopyFromRemoteRequest{} }
func (m *CopyFromRemoteRequest) String() string { return proto.CompactTextString(m) }
func (*CopyFromRemoteRequest) ProtoMessage()    {}
func (*CopyFromRemoteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_78fc9c5a618b7cda, []int{3}
}

func (m *CopyFromRemoteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CopyFromRemoteRequest.Unmarshal(m, b)
}
func (m *CopyFromRemoteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CopyFromRemoteRequest.Marshal(b, m, deterministic)
}
func (m *CopyFromRemoteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CopyFromRemoteRequest.Merge(m, src)
}
func (m *CopyFromRemoteRequest) XXX_Size() int {
	return xxx_messageInfo_CopyFromRemoteRequest.Size(m)
}
func (m *CopyFromRemoteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CopyFromRemoteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CopyFromRemoteRequest proto.InternalMessageInfo

func (m *CopyFromRemoteRequest) GetSftp() *Sftp {
	if m != nil {
		return m.Sftp
	}
	return nil
}

type CopyFromRemoteResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CopyFromRemoteResponse) Reset()         { *m = CopyFromRemoteResponse{} }
func (m *CopyFromRemoteResponse) String() string { return proto.CompactTextString(m) }
func (*CopyFromRemoteResponse) ProtoMessage()    {}
func (*CopyFromRemoteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_78fc9c5a618b7cda, []int{4}
}

func (m *CopyFromRemoteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CopyFromRemoteResponse.Unmarshal(m, b)
}
func (m *CopyFromRemoteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CopyFromRemoteResponse.Marshal(b, m, deterministic)
}
func (m *CopyFromRemoteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CopyFromRemoteResponse.Merge(m, src)
}
func (m *CopyFromRemoteResponse) XXX_Size() int {
	return xxx_messageInfo_CopyFromRemoteResponse.Size(m)
}
func (m *CopyFromRemoteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CopyFromRemoteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CopyFromRemoteResponse proto.InternalMessageInfo

func (m *CopyFromRemoteResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type List struct {
	FileName             string   `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
	FileDir              string   `protobuf:"bytes,2,opt,name=fileDir,proto3" json:"fileDir,omitempty"`
	FileSize             string   `protobuf:"bytes,3,opt,name=fileSize,proto3" json:"fileSize,omitempty"`
	IsDir                string   `protobuf:"bytes,4,opt,name=isDir,proto3" json:"isDir,omitempty"`
	StartDir             string   `protobuf:"bytes,5,opt,name=startDir,proto3" json:"startDir,omitempty"`
	UserName             string   `protobuf:"bytes,6,opt,name=userName,proto3" json:"userName,omitempty"`
	PassWord             string   `protobuf:"bytes,7,opt,name=passWord,proto3" json:"passWord,omitempty"`
	SystemId             string   `protobuf:"bytes,8,opt,name=systemId,proto3" json:"systemId,omitempty"`
	HostPort             string   `protobuf:"bytes,9,opt,name=hostPort,proto3" json:"hostPort,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *List) Reset()         { *m = List{} }
func (m *List) String() string { return proto.CompactTextString(m) }
func (*List) ProtoMessage()    {}
func (*List) Descriptor() ([]byte, []int) {
	return fileDescriptor_78fc9c5a618b7cda, []int{5}
}

func (m *List) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_List.Unmarshal(m, b)
}
func (m *List) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_List.Marshal(b, m, deterministic)
}
func (m *List) XXX_Merge(src proto.Message) {
	xxx_messageInfo_List.Merge(m, src)
}
func (m *List) XXX_Size() int {
	return xxx_messageInfo_List.Size(m)
}
func (m *List) XXX_DiscardUnknown() {
	xxx_messageInfo_List.DiscardUnknown(m)
}

var xxx_messageInfo_List proto.InternalMessageInfo

func (m *List) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *List) GetFileDir() string {
	if m != nil {
		return m.FileDir
	}
	return ""
}

func (m *List) GetFileSize() string {
	if m != nil {
		return m.FileSize
	}
	return ""
}

func (m *List) GetIsDir() string {
	if m != nil {
		return m.IsDir
	}
	return ""
}

func (m *List) GetStartDir() string {
	if m != nil {
		return m.StartDir
	}
	return ""
}

func (m *List) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *List) GetPassWord() string {
	if m != nil {
		return m.PassWord
	}
	return ""
}

func (m *List) GetSystemId() string {
	if m != nil {
		return m.SystemId
	}
	return ""
}

func (m *List) GetHostPort() string {
	if m != nil {
		return m.HostPort
	}
	return ""
}

type GetDirRequest struct {
	List                 *List    `protobuf:"bytes,1,opt,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDirRequest) Reset()         { *m = GetDirRequest{} }
func (m *GetDirRequest) String() string { return proto.CompactTextString(m) }
func (*GetDirRequest) ProtoMessage()    {}
func (*GetDirRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_78fc9c5a618b7cda, []int{6}
}

func (m *GetDirRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDirRequest.Unmarshal(m, b)
}
func (m *GetDirRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDirRequest.Marshal(b, m, deterministic)
}
func (m *GetDirRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDirRequest.Merge(m, src)
}
func (m *GetDirRequest) XXX_Size() int {
	return xxx_messageInfo_GetDirRequest.Size(m)
}
func (m *GetDirRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDirRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDirRequest proto.InternalMessageInfo

func (m *GetDirRequest) GetList() *List {
	if m != nil {
		return m.List
	}
	return nil
}

type GetDirResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDirResponse) Reset()         { *m = GetDirResponse{} }
func (m *GetDirResponse) String() string { return proto.CompactTextString(m) }
func (*GetDirResponse) ProtoMessage()    {}
func (*GetDirResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_78fc9c5a618b7cda, []int{7}
}

func (m *GetDirResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDirResponse.Unmarshal(m, b)
}
func (m *GetDirResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDirResponse.Marshal(b, m, deterministic)
}
func (m *GetDirResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDirResponse.Merge(m, src)
}
func (m *GetDirResponse) XXX_Size() int {
	return xxx_messageInfo_GetDirResponse.Size(m)
}
func (m *GetDirResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDirResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDirResponse proto.InternalMessageInfo

func (m *GetDirResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*Sftp)(nil), "sftp.Sftp")
	proto.RegisterType((*CopyLocalToRemoteRequest)(nil), "sftp.CopyLocalToRemoteRequest")
	proto.RegisterType((*CopyLocalToRemoteResponse)(nil), "sftp.CopyLocalToRemoteResponse")
	proto.RegisterType((*CopyFromRemoteRequest)(nil), "sftp.CopyFromRemoteRequest")
	proto.RegisterType((*CopyFromRemoteResponse)(nil), "sftp.CopyFromRemoteResponse")
	proto.RegisterType((*List)(nil), "sftp.List")
	proto.RegisterType((*GetDirRequest)(nil), "sftp.GetDirRequest")
	proto.RegisterType((*GetDirResponse)(nil), "sftp.GetDirResponse")
}

func init() { proto.RegisterFile("sftp.proto", fileDescriptor_78fc9c5a618b7cda) }

var fileDescriptor_78fc9c5a618b7cda = []byte{
	// 442 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x41, 0x8b, 0xd3, 0x40,
	0x18, 0x25, 0x9a, 0x4d, 0xb6, 0x9f, 0x28, 0x38, 0xae, 0xcb, 0x98, 0x5d, 0x56, 0xc9, 0x69, 0x4f,
	0x75, 0xd9, 0x3d, 0x08, 0xe2, 0x49, 0x65, 0x45, 0x5c, 0x4a, 0x49, 0x0b, 0x82, 0x9e, 0x62, 0xfa,
	0xb5, 0x0e, 0x24, 0x99, 0x38, 0x33, 0x15, 0xea, 0x4f, 0xf4, 0xff, 0x78, 0xf1, 0x24, 0xdf, 0x4c,
	0xc6, 0x36, 0x21, 0x56, 0xf6, 0x96, 0x37, 0x2f, 0x6f, 0xbe, 0x7e, 0xef, 0xbd, 0x06, 0x40, 0x2f,
	0x4d, 0x33, 0x6e, 0x94, 0x34, 0x92, 0x85, 0xf4, 0x9c, 0xfe, 0x0c, 0x20, 0x9c, 0x2d, 0x4d, 0xc3,
	0x12, 0x38, 0x5c, 0x6b, 0x54, 0x75, 0x5e, 0x21, 0x0f, 0x9e, 0x05, 0xe7, 0xa3, 0xec, 0x2f, 0x26,
	0xae, 0xc9, 0xb5, 0xfe, 0x28, 0xd5, 0x82, 0xdf, 0x71, 0x9c, 0xc7, 0xc4, 0xe9, 0x8d, 0x36, 0x58,
	0xbd, 0x5f, 0xf0, 0xbb, 0x8e, 0xf3, 0x98, 0x71, 0x88, 0xbf, 0x4a, 0x6d, 0x3e, 0xe0, 0x86, 0x87,
	0x96, 0xf2, 0x90, 0x54, 0x4b, 0x51, 0xe2, 0x84, 0xa6, 0x1d, 0x38, 0x95, 0xc7, 0xc4, 0xd1, 0x6b,
	0x53, 0xa9, 0x0c, 0x8f, 0x1c, 0xe7, 0x31, 0x3b, 0x85, 0x51, 0x51, 0x0a, 0xac, 0xed, 0x9d, 0xb1,
	0x25, 0xb7, 0x07, 0xe9, 0x4b, 0xe0, 0x6f, 0x64, 0xb3, 0xb9, 0x91, 0x45, 0x5e, 0xce, 0x65, 0x86,
	0x95, 0x34, 0x98, 0xe1, 0xb7, 0x35, 0x6a, 0xc3, 0xce, 0xc0, 0x2e, 0x6c, 0x77, 0xbb, 0x77, 0x09,
	0x63, 0xeb, 0x04, 0x6d, 0x9e, 0x39, 0x23, 0xae, 0xe0, 0xc9, 0x80, 0x56, 0x37, 0xb2, 0xd6, 0xc8,
	0x8e, 0x21, 0x52, 0xa8, 0xd7, 0xa5, 0x69, 0xad, 0x69, 0x51, 0xfa, 0x02, 0x1e, 0x93, 0xe8, 0x5a,
	0xc9, 0xea, 0x76, 0xd3, 0x2e, 0xe0, 0xb8, 0x2f, 0xfc, 0xcf, 0xa8, 0xdf, 0x01, 0x84, 0x37, 0x42,
	0x9b, 0x8e, 0x75, 0x41, 0xcf, 0x3a, 0x0e, 0x31, 0x3d, 0xbf, 0x15, 0xaa, 0xcd, 0xc9, 0x43, 0xaf,
	0x9a, 0x89, 0x1f, 0xe8, 0x63, 0xf2, 0x98, 0x1d, 0xc1, 0x81, 0xd0, 0xa4, 0x71, 0x21, 0x39, 0x60,
	0x83, 0x35, 0xb9, 0x32, 0x44, 0xb4, 0x11, 0x79, 0xec, 0xcb, 0x62, 0x7f, 0x43, 0xb4, 0x2d, 0xcb,
	0xa4, 0x5f, 0x96, 0x78, 0x4f, 0x59, 0x0e, 0x7b, 0x65, 0xd9, 0x8d, 0x7d, 0xd4, 0x8d, 0x3d, 0x7d,
	0x0e, 0xf7, 0xdf, 0x21, 0x4d, 0xde, 0xf1, 0xb7, 0x14, 0xda, 0x74, 0xfd, 0x25, 0x7b, 0x32, 0x7b,
	0x9e, 0x9e, 0xc3, 0x03, 0x2f, 0xd8, 0xef, 0xeb, 0xe5, 0x2f, 0xfa, 0x03, 0x5c, 0xcf, 0xa7, 0x2c,
	0xeb, 0x67, 0x39, 0x43, 0xf5, 0x5d, 0x14, 0xc8, 0x4e, 0xdc, 0xed, 0x83, 0x41, 0x27, 0xa7, 0xc3,
	0x64, 0x3b, 0xf4, 0xf3, 0x40, 0x21, 0xfd, 0xb5, 0x67, 0x5b, 0xe5, 0x50, 0x61, 0x93, 0xa7, 0xff,
	0xe4, 0xdb, 0xcb, 0x5f, 0x79, 0x53, 0x68, 0x6f, 0x51, 0xaf, 0xd8, 0x23, 0xa7, 0xe8, 0x38, 0x95,
	0x1c, 0x75, 0x0f, 0x9d, 0xf6, 0x22, 0x78, 0x7d, 0x02, 0x0f, 0x0b, 0x59, 0xb9, 0x6f, 0xc1, 0x78,
	0x25, 0xed, 0x5b, 0xd3, 0xe0, 0x93, 0xad, 0xe7, 0x97, 0xc8, 0x1e, 0x5f, 0xfd, 0x09, 0x00, 0x00,
	0xff, 0xff, 0xdb, 0xdb, 0xeb, 0x2c, 0x30, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SFTPClient is the client API for SFTP service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SFTPClient interface {
	CopyFromRemoteService(ctx context.Context, in *CopyFromRemoteRequest, opts ...grpc.CallOption) (*CopyFromRemoteResponse, error)
	CopyLocalToRemoteService(ctx context.Context, in *CopyLocalToRemoteRequest, opts ...grpc.CallOption) (*CopyLocalToRemoteResponse, error)
	GetDirListing(ctx context.Context, in *GetDirRequest, opts ...grpc.CallOption) (SFTP_GetDirListingClient, error)
}

type sFTPClient struct {
	cc *grpc.ClientConn
}

func NewSFTPClient(cc *grpc.ClientConn) SFTPClient {
	return &sFTPClient{cc}
}

func (c *sFTPClient) CopyFromRemoteService(ctx context.Context, in *CopyFromRemoteRequest, opts ...grpc.CallOption) (*CopyFromRemoteResponse, error) {
	out := new(CopyFromRemoteResponse)
	err := c.cc.Invoke(ctx, "/sftp.SFTP/CopyFromRemoteService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sFTPClient) CopyLocalToRemoteService(ctx context.Context, in *CopyLocalToRemoteRequest, opts ...grpc.CallOption) (*CopyLocalToRemoteResponse, error) {
	out := new(CopyLocalToRemoteResponse)
	err := c.cc.Invoke(ctx, "/sftp.SFTP/CopyLocalToRemoteService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sFTPClient) GetDirListing(ctx context.Context, in *GetDirRequest, opts ...grpc.CallOption) (SFTP_GetDirListingClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SFTP_serviceDesc.Streams[0], "/sftp.SFTP/GetDirListing", opts...)
	if err != nil {
		return nil, err
	}
	x := &sFTPGetDirListingClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SFTP_GetDirListingClient interface {
	Recv() (*GetDirResponse, error)
	grpc.ClientStream
}

type sFTPGetDirListingClient struct {
	grpc.ClientStream
}

func (x *sFTPGetDirListingClient) Recv() (*GetDirResponse, error) {
	m := new(GetDirResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SFTPServer is the server API for SFTP service.
type SFTPServer interface {
	CopyFromRemoteService(context.Context, *CopyFromRemoteRequest) (*CopyFromRemoteResponse, error)
	CopyLocalToRemoteService(context.Context, *CopyLocalToRemoteRequest) (*CopyLocalToRemoteResponse, error)
	GetDirListing(*GetDirRequest, SFTP_GetDirListingServer) error
}

// UnimplementedSFTPServer can be embedded to have forward compatible implementations.
type UnimplementedSFTPServer struct {
}

func (*UnimplementedSFTPServer) CopyFromRemoteService(ctx context.Context, req *CopyFromRemoteRequest) (*CopyFromRemoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CopyFromRemoteService not implemented")
}
func (*UnimplementedSFTPServer) CopyLocalToRemoteService(ctx context.Context, req *CopyLocalToRemoteRequest) (*CopyLocalToRemoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CopyLocalToRemoteService not implemented")
}
func (*UnimplementedSFTPServer) GetDirListing(req *GetDirRequest, srv SFTP_GetDirListingServer) error {
	return status.Errorf(codes.Unimplemented, "method GetDirListing not implemented")
}

func RegisterSFTPServer(s *grpc.Server, srv SFTPServer) {
	s.RegisterService(&_SFTP_serviceDesc, srv)
}

func _SFTP_CopyFromRemoteService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CopyFromRemoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SFTPServer).CopyFromRemoteService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sftp.SFTP/CopyFromRemoteService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SFTPServer).CopyFromRemoteService(ctx, req.(*CopyFromRemoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SFTP_CopyLocalToRemoteService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CopyLocalToRemoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SFTPServer).CopyLocalToRemoteService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sftp.SFTP/CopyLocalToRemoteService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SFTPServer).CopyLocalToRemoteService(ctx, req.(*CopyLocalToRemoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SFTP_GetDirListing_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetDirRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SFTPServer).GetDirListing(m, &sFTPGetDirListingServer{stream})
}

type SFTP_GetDirListingServer interface {
	Send(*GetDirResponse) error
	grpc.ServerStream
}

type sFTPGetDirListingServer struct {
	grpc.ServerStream
}

func (x *sFTPGetDirListingServer) Send(m *GetDirResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _SFTP_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sftp.SFTP",
	HandlerType: (*SFTPServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CopyFromRemoteService",
			Handler:    _SFTP_CopyFromRemoteService_Handler,
		},
		{
			MethodName: "CopyLocalToRemoteService",
			Handler:    _SFTP_CopyLocalToRemoteService_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetDirListing",
			Handler:       _SFTP_GetDirListing_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sftp.proto",
}
