package org.iplantc.service.jobs.model.enumerations;

public enum StartupScriptJobVariableType
{
	// job value macros
	AGAVE_JOB_NAME,
	AGAVE_JOB_ID,
	AGAVE_JOB_APP_ID,
	AGAVE_JOB_EXECUTION_SYSTEM,
	AGAVE_JOB_BATCH_QUEUE,
	AGAVE_JOB_BATCH_QUEUE_EFFECTIVE_NAME,
	AGAVE_JOB_ARCHIVE_PATH,
	AGAVE_JOB_OWNER,
	AGAVE_JOB_TENANT,
	AGAVE_JOB_WORK_PATH;
}
