###############################################################
# Persistence Services
# docker-compose.persistence.yml
#
# This is the orchestration file to start Agave's persistence
# services. Namely, 2 mysql databases, a message queue. The APIs are accessible behind a reverse proxy which
# shields them from the outside world.
# Containers performing data operations are assigned a partition
# of the default GridFTP and FTP port ranges to enable proper
# operation of the protocol from within each container.
#
###############################################################
---
version: '3.3'

volumes:
  mysql_core_data:
  mongo_data:
  beanstalkd_data:

services:

  mysql-core:
    image: agaveplatform/agave-mariadb:${AGAVE_VERSION}
    ports:
      - '3306:3306'
    volumes:
      - mysql_core_data:/var/lib/mysql
    env_file:
      - configs/mysql-core.conf
    labels:
      - "traefik.enable=false"
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 1g
        reservations:
          memory: 256M

  mongodb:
    image: agaveplatform/mongodb:4.2.8
    hostname: mongodb
    env_file:
      - configs/mongodb.conf
    volumes:
      - mongo_data:/data
    ports:
      - '27017:27017'
    labels:
      - "traefik.enable=false"
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  beanstalkd:
    image: agaveplatform/beanstalkd:latest
    command: /usr/bin/beanstalkd -b /var/lib/beanstalkd/binlog
    hostname: beanstalkd
    ports:
      - '11300:11300'
    labels:
      - "traefik.enable=false"
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 512m
        reservations:
          memory: 128m

  beanstalkd-console:
    image: kusmierz/beanstalk-console:latest
    ports:
      - '9999:80'
    labels:
      - "traefik.enable=false"
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 512m
        reservations:
          memory: 128m

#  maildev:
#    image: agaveplatform/maildev:latest
#    ports:
#      - "38080:80"
#      - "25"
#    env_file:
#      - configs/maildev.conf
#    volumes:
#      - ./persistence-services/maildev/rules.json:/data/rules.json