// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/proto/sftp.proto

package com.proto.go.sftp;

public interface CopyFromRemoteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sftp.CopyFromRemoteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.sftp.Sftp sftp = 1;</code>
   */
  boolean hasSftp();
  /**
   * <code>.sftp.Sftp sftp = 1;</code>
   */
  Sftp getSftp();
  /**
   * <code>.sftp.Sftp sftp = 1;</code>
   */
  SftpOrBuilder getSftpOrBuilder();
}
