// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/proto/sftp.proto

package com.proto.go.sftp;

public interface GetDirRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sftp.GetDirRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.sftp.List list = 1;</code>
   */
  boolean hasList();
  /**
   * <code>.sftp.List list = 1;</code>
   */
  List getList();
  /**
   * <code>.sftp.List list = 1;</code>
   */
  ListOrBuilder getListOrBuilder();
}
