// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/proto/sftp.proto

package com.proto.go.sftp;

public interface ListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sftp.List)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string fileName = 1;</code>
   */
  String getFileName();
  /**
   * <code>string fileName = 1;</code>
   */
  com.google.protobuf.ByteString
      getFileNameBytes();

  /**
   * <code>string fileDir = 2;</code>
   */
  String getFileDir();
  /**
   * <code>string fileDir = 2;</code>
   */
  com.google.protobuf.ByteString
      getFileDirBytes();

  /**
   * <code>string fileSize = 3;</code>
   */
  String getFileSize();
  /**
   * <code>string fileSize = 3;</code>
   */
  com.google.protobuf.ByteString
      getFileSizeBytes();

  /**
   * <code>string isDir = 4;</code>
   */
  String getIsDir();
  /**
   * <code>string isDir = 4;</code>
   */
  com.google.protobuf.ByteString
      getIsDirBytes();

  /**
   * <code>string startDir = 5;</code>
   */
  String getStartDir();
  /**
   * <code>string startDir = 5;</code>
   */
  com.google.protobuf.ByteString
      getStartDirBytes();

  /**
   * <code>string userName = 6;</code>
   */
  String getUserName();
  /**
   * <code>string userName = 6;</code>
   */
  com.google.protobuf.ByteString
      getUserNameBytes();

  /**
   * <code>string passWord = 7;</code>
   */
  String getPassWord();
  /**
   * <code>string passWord = 7;</code>
   */
  com.google.protobuf.ByteString
      getPassWordBytes();

  /**
   * <code>string systemId = 8;</code>
   */
  String getSystemId();
  /**
   * <code>string systemId = 8;</code>
   */
  com.google.protobuf.ByteString
      getSystemIdBytes();

  /**
   * <code>string hostPort = 9;</code>
   */
  String getHostPort();
  /**
   * <code>string hostPort = 9;</code>
   */
  com.google.protobuf.ByteString
      getHostPortBytes();
}
