// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/proto/sftp.proto

package com.proto.go.sftp;

/**
 * Protobuf type {@code sftp.List}
 */
public  final class List extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:sftp.List)
    ListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use List.newBuilder() to construct.
  private List(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private List() {
    fileName_ = "";
    fileDir_ = "";
    fileSize_ = "";
    isDir_ = "";
    startDir_ = "";
    userName_ = "";
    passWord_ = "";
    systemId_ = "";
    hostPort_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new List();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private List(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            fileName_ = s;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            fileDir_ = s;
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            fileSize_ = s;
            break;
          }
          case 34: {
            String s = input.readStringRequireUtf8();

            isDir_ = s;
            break;
          }
          case 42: {
            String s = input.readStringRequireUtf8();

            startDir_ = s;
            break;
          }
          case 50: {
            String s = input.readStringRequireUtf8();

            userName_ = s;
            break;
          }
          case 58: {
            String s = input.readStringRequireUtf8();

            passWord_ = s;
            break;
          }
          case 66: {
            String s = input.readStringRequireUtf8();

            systemId_ = s;
            break;
          }
          case 74: {
            String s = input.readStringRequireUtf8();

            hostPort_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.proto.go.sftp.SftpOuterClass.internal_static_sftp_List_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.proto.go.sftp.SftpOuterClass.internal_static_sftp_List_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            List.class, Builder.class);
  }

  public static final int FILENAME_FIELD_NUMBER = 1;
  private volatile Object fileName_;
  /**
   * <code>string fileName = 1;</code>
   */
  public String getFileName() {
    Object ref = fileName_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      fileName_ = s;
      return s;
    }
  }
  /**
   * <code>string fileName = 1;</code>
   */
  public com.google.protobuf.ByteString
      getFileNameBytes() {
    Object ref = fileName_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      fileName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FILEDIR_FIELD_NUMBER = 2;
  private volatile Object fileDir_;
  /**
   * <code>string fileDir = 2;</code>
   */
  public String getFileDir() {
    Object ref = fileDir_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      fileDir_ = s;
      return s;
    }
  }
  /**
   * <code>string fileDir = 2;</code>
   */
  public com.google.protobuf.ByteString
      getFileDirBytes() {
    Object ref = fileDir_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      fileDir_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FILESIZE_FIELD_NUMBER = 3;
  private volatile Object fileSize_;
  /**
   * <code>string fileSize = 3;</code>
   */
  public String getFileSize() {
    Object ref = fileSize_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      fileSize_ = s;
      return s;
    }
  }
  /**
   * <code>string fileSize = 3;</code>
   */
  public com.google.protobuf.ByteString
      getFileSizeBytes() {
    Object ref = fileSize_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      fileSize_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ISDIR_FIELD_NUMBER = 4;
  private volatile Object isDir_;
  /**
   * <code>string isDir = 4;</code>
   */
  public String getIsDir() {
    Object ref = isDir_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      isDir_ = s;
      return s;
    }
  }
  /**
   * <code>string isDir = 4;</code>
   */
  public com.google.protobuf.ByteString
      getIsDirBytes() {
    Object ref = isDir_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      isDir_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STARTDIR_FIELD_NUMBER = 5;
  private volatile Object startDir_;
  /**
   * <code>string startDir = 5;</code>
   */
  public String getStartDir() {
    Object ref = startDir_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      startDir_ = s;
      return s;
    }
  }
  /**
   * <code>string startDir = 5;</code>
   */
  public com.google.protobuf.ByteString
      getStartDirBytes() {
    Object ref = startDir_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      startDir_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USERNAME_FIELD_NUMBER = 6;
  private volatile Object userName_;
  /**
   * <code>string userName = 6;</code>
   */
  public String getUserName() {
    Object ref = userName_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      userName_ = s;
      return s;
    }
  }
  /**
   * <code>string userName = 6;</code>
   */
  public com.google.protobuf.ByteString
      getUserNameBytes() {
    Object ref = userName_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      userName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PASSWORD_FIELD_NUMBER = 7;
  private volatile Object passWord_;
  /**
   * <code>string passWord = 7;</code>
   */
  public String getPassWord() {
    Object ref = passWord_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      passWord_ = s;
      return s;
    }
  }
  /**
   * <code>string passWord = 7;</code>
   */
  public com.google.protobuf.ByteString
      getPassWordBytes() {
    Object ref = passWord_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      passWord_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SYSTEMID_FIELD_NUMBER = 8;
  private volatile Object systemId_;
  /**
   * <code>string systemId = 8;</code>
   */
  public String getSystemId() {
    Object ref = systemId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      systemId_ = s;
      return s;
    }
  }
  /**
   * <code>string systemId = 8;</code>
   */
  public com.google.protobuf.ByteString
      getSystemIdBytes() {
    Object ref = systemId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      systemId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HOSTPORT_FIELD_NUMBER = 9;
  private volatile Object hostPort_;
  /**
   * <code>string hostPort = 9;</code>
   */
  public String getHostPort() {
    Object ref = hostPort_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      hostPort_ = s;
      return s;
    }
  }
  /**
   * <code>string hostPort = 9;</code>
   */
  public com.google.protobuf.ByteString
      getHostPortBytes() {
    Object ref = hostPort_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      hostPort_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getFileNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fileName_);
    }
    if (!getFileDirBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, fileDir_);
    }
    if (!getFileSizeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, fileSize_);
    }
    if (!getIsDirBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, isDir_);
    }
    if (!getStartDirBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, startDir_);
    }
    if (!getUserNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, userName_);
    }
    if (!getPassWordBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, passWord_);
    }
    if (!getSystemIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, systemId_);
    }
    if (!getHostPortBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, hostPort_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getFileNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, fileName_);
    }
    if (!getFileDirBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, fileDir_);
    }
    if (!getFileSizeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, fileSize_);
    }
    if (!getIsDirBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, isDir_);
    }
    if (!getStartDirBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, startDir_);
    }
    if (!getUserNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, userName_);
    }
    if (!getPassWordBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, passWord_);
    }
    if (!getSystemIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, systemId_);
    }
    if (!getHostPortBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, hostPort_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof List)) {
      return super.equals(obj);
    }
    List other = (List) obj;

    if (!getFileName()
        .equals(other.getFileName())) return false;
    if (!getFileDir()
        .equals(other.getFileDir())) return false;
    if (!getFileSize()
        .equals(other.getFileSize())) return false;
    if (!getIsDir()
        .equals(other.getIsDir())) return false;
    if (!getStartDir()
        .equals(other.getStartDir())) return false;
    if (!getUserName()
        .equals(other.getUserName())) return false;
    if (!getPassWord()
        .equals(other.getPassWord())) return false;
    if (!getSystemId()
        .equals(other.getSystemId())) return false;
    if (!getHostPort()
        .equals(other.getHostPort())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FILENAME_FIELD_NUMBER;
    hash = (53 * hash) + getFileName().hashCode();
    hash = (37 * hash) + FILEDIR_FIELD_NUMBER;
    hash = (53 * hash) + getFileDir().hashCode();
    hash = (37 * hash) + FILESIZE_FIELD_NUMBER;
    hash = (53 * hash) + getFileSize().hashCode();
    hash = (37 * hash) + ISDIR_FIELD_NUMBER;
    hash = (53 * hash) + getIsDir().hashCode();
    hash = (37 * hash) + STARTDIR_FIELD_NUMBER;
    hash = (53 * hash) + getStartDir().hashCode();
    hash = (37 * hash) + USERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getUserName().hashCode();
    hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
    hash = (53 * hash) + getPassWord().hashCode();
    hash = (37 * hash) + SYSTEMID_FIELD_NUMBER;
    hash = (53 * hash) + getSystemId().hashCode();
    hash = (37 * hash) + HOSTPORT_FIELD_NUMBER;
    hash = (53 * hash) + getHostPort().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static List parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static List parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static List parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static List parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static List parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static List parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static List parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static List parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static List parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static List parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static List parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static List parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(List prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code sftp.List}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:sftp.List)
      com.proto.go.sftp.ListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.proto.go.sftp.SftpOuterClass.internal_static_sftp_List_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.proto.go.sftp.SftpOuterClass.internal_static_sftp_List_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              List.class, Builder.class);
    }

    // Construct using com.proto.go.sftp.List.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      fileName_ = "";

      fileDir_ = "";

      fileSize_ = "";

      isDir_ = "";

      startDir_ = "";

      userName_ = "";

      passWord_ = "";

      systemId_ = "";

      hostPort_ = "";

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.proto.go.sftp.SftpOuterClass.internal_static_sftp_List_descriptor;
    }

    @Override
    public List getDefaultInstanceForType() {
      return List.getDefaultInstance();
    }

    @Override
    public List build() {
      List result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public List buildPartial() {
      List result = new List(this);
      result.fileName_ = fileName_;
      result.fileDir_ = fileDir_;
      result.fileSize_ = fileSize_;
      result.isDir_ = isDir_;
      result.startDir_ = startDir_;
      result.userName_ = userName_;
      result.passWord_ = passWord_;
      result.systemId_ = systemId_;
      result.hostPort_ = hostPort_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof List) {
        return mergeFrom((List)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(List other) {
      if (other == List.getDefaultInstance()) return this;
      if (!other.getFileName().isEmpty()) {
        fileName_ = other.fileName_;
        onChanged();
      }
      if (!other.getFileDir().isEmpty()) {
        fileDir_ = other.fileDir_;
        onChanged();
      }
      if (!other.getFileSize().isEmpty()) {
        fileSize_ = other.fileSize_;
        onChanged();
      }
      if (!other.getIsDir().isEmpty()) {
        isDir_ = other.isDir_;
        onChanged();
      }
      if (!other.getStartDir().isEmpty()) {
        startDir_ = other.startDir_;
        onChanged();
      }
      if (!other.getUserName().isEmpty()) {
        userName_ = other.userName_;
        onChanged();
      }
      if (!other.getPassWord().isEmpty()) {
        passWord_ = other.passWord_;
        onChanged();
      }
      if (!other.getSystemId().isEmpty()) {
        systemId_ = other.systemId_;
        onChanged();
      }
      if (!other.getHostPort().isEmpty()) {
        hostPort_ = other.hostPort_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      List parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (List) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object fileName_ = "";
    /**
     * <code>string fileName = 1;</code>
     */
    public String getFileName() {
      Object ref = fileName_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        fileName_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string fileName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFileNameBytes() {
      Object ref = fileName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        fileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string fileName = 1;</code>
     */
    public Builder setFileName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      fileName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string fileName = 1;</code>
     */
    public Builder clearFileName() {
      
      fileName_ = getDefaultInstance().getFileName();
      onChanged();
      return this;
    }
    /**
     * <code>string fileName = 1;</code>
     */
    public Builder setFileNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      fileName_ = value;
      onChanged();
      return this;
    }

    private Object fileDir_ = "";
    /**
     * <code>string fileDir = 2;</code>
     */
    public String getFileDir() {
      Object ref = fileDir_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        fileDir_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string fileDir = 2;</code>
     */
    public com.google.protobuf.ByteString
        getFileDirBytes() {
      Object ref = fileDir_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        fileDir_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string fileDir = 2;</code>
     */
    public Builder setFileDir(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      fileDir_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string fileDir = 2;</code>
     */
    public Builder clearFileDir() {
      
      fileDir_ = getDefaultInstance().getFileDir();
      onChanged();
      return this;
    }
    /**
     * <code>string fileDir = 2;</code>
     */
    public Builder setFileDirBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      fileDir_ = value;
      onChanged();
      return this;
    }

    private Object fileSize_ = "";
    /**
     * <code>string fileSize = 3;</code>
     */
    public String getFileSize() {
      Object ref = fileSize_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        fileSize_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string fileSize = 3;</code>
     */
    public com.google.protobuf.ByteString
        getFileSizeBytes() {
      Object ref = fileSize_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        fileSize_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string fileSize = 3;</code>
     */
    public Builder setFileSize(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      fileSize_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string fileSize = 3;</code>
     */
    public Builder clearFileSize() {
      
      fileSize_ = getDefaultInstance().getFileSize();
      onChanged();
      return this;
    }
    /**
     * <code>string fileSize = 3;</code>
     */
    public Builder setFileSizeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      fileSize_ = value;
      onChanged();
      return this;
    }

    private Object isDir_ = "";
    /**
     * <code>string isDir = 4;</code>
     */
    public String getIsDir() {
      Object ref = isDir_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        isDir_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string isDir = 4;</code>
     */
    public com.google.protobuf.ByteString
        getIsDirBytes() {
      Object ref = isDir_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        isDir_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string isDir = 4;</code>
     */
    public Builder setIsDir(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      isDir_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string isDir = 4;</code>
     */
    public Builder clearIsDir() {
      
      isDir_ = getDefaultInstance().getIsDir();
      onChanged();
      return this;
    }
    /**
     * <code>string isDir = 4;</code>
     */
    public Builder setIsDirBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      isDir_ = value;
      onChanged();
      return this;
    }

    private Object startDir_ = "";
    /**
     * <code>string startDir = 5;</code>
     */
    public String getStartDir() {
      Object ref = startDir_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        startDir_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string startDir = 5;</code>
     */
    public com.google.protobuf.ByteString
        getStartDirBytes() {
      Object ref = startDir_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        startDir_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string startDir = 5;</code>
     */
    public Builder setStartDir(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      startDir_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string startDir = 5;</code>
     */
    public Builder clearStartDir() {
      
      startDir_ = getDefaultInstance().getStartDir();
      onChanged();
      return this;
    }
    /**
     * <code>string startDir = 5;</code>
     */
    public Builder setStartDirBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      startDir_ = value;
      onChanged();
      return this;
    }

    private Object userName_ = "";
    /**
     * <code>string userName = 6;</code>
     */
    public String getUserName() {
      Object ref = userName_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        userName_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string userName = 6;</code>
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      Object ref = userName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string userName = 6;</code>
     */
    public Builder setUserName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string userName = 6;</code>
     */
    public Builder clearUserName() {
      
      userName_ = getDefaultInstance().getUserName();
      onChanged();
      return this;
    }
    /**
     * <code>string userName = 6;</code>
     */
    public Builder setUserNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userName_ = value;
      onChanged();
      return this;
    }

    private Object passWord_ = "";
    /**
     * <code>string passWord = 7;</code>
     */
    public String getPassWord() {
      Object ref = passWord_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        passWord_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string passWord = 7;</code>
     */
    public com.google.protobuf.ByteString
        getPassWordBytes() {
      Object ref = passWord_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        passWord_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string passWord = 7;</code>
     */
    public Builder setPassWord(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      passWord_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string passWord = 7;</code>
     */
    public Builder clearPassWord() {
      
      passWord_ = getDefaultInstance().getPassWord();
      onChanged();
      return this;
    }
    /**
     * <code>string passWord = 7;</code>
     */
    public Builder setPassWordBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      passWord_ = value;
      onChanged();
      return this;
    }

    private Object systemId_ = "";
    /**
     * <code>string systemId = 8;</code>
     */
    public String getSystemId() {
      Object ref = systemId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        systemId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string systemId = 8;</code>
     */
    public com.google.protobuf.ByteString
        getSystemIdBytes() {
      Object ref = systemId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        systemId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string systemId = 8;</code>
     */
    public Builder setSystemId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      systemId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string systemId = 8;</code>
     */
    public Builder clearSystemId() {
      
      systemId_ = getDefaultInstance().getSystemId();
      onChanged();
      return this;
    }
    /**
     * <code>string systemId = 8;</code>
     */
    public Builder setSystemIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      systemId_ = value;
      onChanged();
      return this;
    }

    private Object hostPort_ = "";
    /**
     * <code>string hostPort = 9;</code>
     */
    public String getHostPort() {
      Object ref = hostPort_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        hostPort_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string hostPort = 9;</code>
     */
    public com.google.protobuf.ByteString
        getHostPortBytes() {
      Object ref = hostPort_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        hostPort_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string hostPort = 9;</code>
     */
    public Builder setHostPort(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      hostPort_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string hostPort = 9;</code>
     */
    public Builder clearHostPort() {
      
      hostPort_ = getDefaultInstance().getHostPort();
      onChanged();
      return this;
    }
    /**
     * <code>string hostPort = 9;</code>
     */
    public Builder setHostPortBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      hostPort_ = value;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:sftp.List)
  }

  // @@protoc_insertion_point(class_scope:sftp.List)
  private static final List DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new List();
  }

  public static List getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<List>
      PARSER = new com.google.protobuf.AbstractParser<List>() {
    @Override
    public List parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new List(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<List> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<List> getParserForType() {
    return PARSER;
  }

  @Override
  public List getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

