// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/proto/sftp.proto

package com.proto.go.sftp;

public interface SftpOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sftp.Sftp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   */
  String getUsername();
  /**
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string passWord = 2;</code>
   */
  String getPassWord();
  /**
   * <code>string passWord = 2;</code>
   */
  com.google.protobuf.ByteString
      getPassWordBytes();

  /**
   * <code>string systemId = 3;</code>
   */
  String getSystemId();
  /**
   * <code>string systemId = 3;</code>
   */
  com.google.protobuf.ByteString
      getSystemIdBytes();

  /**
   * <code>string hostKey = 4;</code>
   */
  String getHostKey();
  /**
   * <code>string hostKey = 4;</code>
   */
  com.google.protobuf.ByteString
      getHostKeyBytes();

  /**
   * <code>string fileName = 5;</code>
   */
  String getFileName();
  /**
   * <code>string fileName = 5;</code>
   */
  com.google.protobuf.ByteString
      getFileNameBytes();

  /**
   * <code>string hostPort = 6;</code>
   */
  String getHostPort();
  /**
   * <code>string hostPort = 6;</code>
   */
  com.google.protobuf.ByteString
      getHostPortBytes();

  /**
   * <code>string clientKey = 7;</code>
   */
  String getClientKey();
  /**
   * <code>string clientKey = 7;</code>
   */
  com.google.protobuf.ByteString
      getClientKeyBytes();
}
