package org.agaveplatform.service.transfers.resources;

import io.vertx.core.AbstractVerticle;
import io.vertx.core.CompositeFuture;
import io.vertx.core.Future;
import io.vertx.core.http.HttpServer;
import io.vertx.core.http.HttpServerResponse;
import io.vertx.core.json.JsonArray;
import io.vertx.core.json.JsonObject;
import io.vertx.ext.auth.PubSecKeyOptions;
import io.vertx.ext.auth.jwt.JWTAuth;
import io.vertx.ext.auth.jwt.JWTAuthOptions;
import io.vertx.ext.jdbc.JDBCClient;
import io.vertx.ext.sql.SQLConnection;
import io.vertx.ext.sql.SQLOptions;
import io.vertx.ext.sql.UpdateResult;
import io.vertx.ext.web.Router;
import io.vertx.ext.web.RoutingContext;
import io.vertx.ext.web.handler.BodyHandler;
import io.vertx.ext.web.handler.impl.AgaveJWTAuthHandlerImpl;
import java.util.stream.Collectors;
import org.iplantc.service.transfer.model.TransferTask;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.List;
import java.util.NoSuchElementException;

import static org.agaveplatform.service.transfers.util.ActionHelper.*;
import static org.agaveplatform.service.transfers.util.AuthHelper.authenticate;

public class TransferServiceVertical extends AbstractVerticle {
    private static Logger log = LoggerFactory.getLogger(TransferServiceVertical.class);

    private HttpServer server;
    private JDBCClient jdbc;
    private JWTAuth authProvider;
    private JsonObject config;

    @Override
    public void start(Future<Void> fut) {
        // set the config from the main vertical
        setConfig(config());

        // define our routes
        Router router = Router.router(vertx);
        // Bind "/" to our hello message - so we are still compatible.
        router.route("/").handler(routingContext -> {
            HttpServerResponse response = routingContext.response();
            JsonObject message = new JsonObject();
            response
                    .putHeader("content-type", "application/json")
                    .end(message.encodePrettily());
        });

        // create a jwt auth provider and apply it as the first handler for all routes
        JWTAuth jwt = getAuthProvider();
        router.route("/api/transfers*").handler(new AgaveJWTAuthHandlerImpl(authProvider, (String)null));

        // define the service routes
        router.get("/api/transfers").handler(this::getAll);
        router.get("/api/transfers/:id").handler(this::getOne);
        router.route("/api/transfers*").handler(BodyHandler.create());
        router.post("/api/transfers").handler(this::addOne);
        router.delete("/api/transfers/:id").handler(this::deleteOne);
        router.put("/api/transfers/:id").handler(this::updateOne);


        // init our db connection from the pool
        jdbc = JDBCClient.createShared(vertx, config, "agave_io");
        connect()
                .compose(connection -> {
                    Future<Void> future = Future.future();
                    createTableIfNeeded(connection)
                            .compose(this::createSomeDataIfNone)
                            .setHandler(x -> {
                                connection.close();
                                future.handle(x.mapEmpty());
                            });
                    return future;
                })
                .compose(v -> createHttpServer(config, router))
                .setHandler(fut);
    }

    private Future<Void> createHttpServer(JsonObject config, Router router) {
        Future<Void> future = Future.future();
        int port = config.getInteger("HTTP_PORT", 8085);

        log.info("Starting TransferServiceVertical on port " + port);

        vertx
            .createHttpServer()
            .requestHandler(router::accept)
            .listen(
                port,
                res -> future.handle(res.mapEmpty())
            );

        return future;
    }

    private Future<SQLConnection> connect() {
        Future<SQLConnection> future = Future.future();
        jdbc.getConnection(ar ->
                future.handle(ar.map(c ->
                                c.setOptions(new SQLOptions().setAutoGeneratedKeys(true))
                        )
                )
        );
        return future;
    }


    private Future<TransferTask> insert(SQLConnection connection, TransferTask transferTask, boolean closeConnection) {
        Future<TransferTask> future = Future.future();
        String sql = "INSERT INTO TransferTasks (source, dest, owner, tenant_id, created, last_updated, uuid) VALUES (?, ?, ?, ?, ?, ?, ?)";
        connection.updateWithParams(sql,
                new JsonArray()
                        .add(transferTask.getSource())
                        .add(transferTask.getDest())
                        .add(transferTask.getOwner())
                        .add(transferTask.getTenantId())
                        .add(transferTask.getCreated())
                        .add(transferTask.getLastUpdated())
                        .add(transferTask.getUuid()),
                ar -> {
                    if (closeConnection) {
                        connection.close();
                    }
                    future.handle(
                            ar.map(res -> {
                                TransferTask t = new TransferTask(transferTask.getSource(), transferTask.getDest());
                                t.setId(res.getKeys().getLong(0));
                                return t;
                            })
                    );
                }
        );
        return future;
    }

    private Future<List<TransferTask>> query(SQLConnection connection) {
        Future<List<TransferTask>> future = Future.future();
        connection.query("SELECT * FROM transferTasks", result -> {
                    connection.close();
                    future.handle(
                            result.map(rs -> rs.getRows().stream().map(TransferTask::new).collect(Collectors.toList()))
                    );
                }
        );
        return future;
    }

    private Future<TransferTask> queryOne(SQLConnection connection, String id) {
        Future<TransferTask> future = Future.future();
        String sql = "SELECT * FROM transferTasks WHERE id = ?";
        connection.queryWithParams(sql, new JsonArray().add(Integer.valueOf(id)), result -> {
            connection.close();
            future.handle(
                    result.map(rs -> {
                        List<JsonObject> rows = rs.getRows();
                        if (rows.size() == 0) {
                            throw new NoSuchElementException("No transferTask with id " + id);
                        } else {
                            JsonObject row = rows.get(0);
                            return new TransferTask(row);
                        }
                    })
            );
        });
        return future;
    }

    private Future<Void> update(SQLConnection connection, String id, TransferTask transferTask) {
        Future<Void> future = Future.future();
        String sql = "UPDATE transferTasks SET title = ?, url = ? WHERE id = ?";
        connection.updateWithParams(sql, new JsonArray()
                        .add(transferTask.getStatus())
                        .add(transferTask.getAttempts())
                        .add(transferTask.getTotalSize())
                        .add(transferTask.getTotalFiles())
                        .add(transferTask.getTotalSkippedFiles())
                        .add(transferTask.getBytesTransferred())
                        .add(transferTask.getLastUpdated())
                        .add(Integer.valueOf(id)),
                ar -> {
                    connection.close();
                    if (ar.failed()) {
                        future.fail(ar.cause());
                    } else {
                        UpdateResult ur = ar.result();
                        if (ur.getUpdated() == 0) {
                            future.fail(new NoSuchElementException("No transferTask with id " + id));
                        } else {
                            future.complete();
                        }
                    }
                });
        return future;
    }

    private Future<Void> delete(SQLConnection connection, String id) {
        Future<Void> future = Future.future();
        String sql = "DELETE FROM TransferTasks WHERE id = ?";
        connection.updateWithParams(sql,
                new JsonArray().add(Integer.valueOf(id)),
                ar -> {
                    connection.close();
                    if (ar.failed()) {
                        future.fail(ar.cause());
                    } else {
                        if (ar.result().getUpdated() == 0) {
                            future.fail(new NoSuchElementException("Unknown transferTask " + id));
                        } else {
                            future.complete();
                        }
                    }
                }
        );
        return future;
    }

    private Future<SQLConnection> createTableIfNeeded(SQLConnection connection) {
        Future<SQLConnection> future = Future.future();
        vertx.fileSystem().readFile("tables.sql", ar -> {
            if (ar.failed()) {
                future.fail(ar.cause());
            } else {
                connection.execute(ar.result().toString(),
                        ar2 -> future.handle(ar2.map(connection))
                );
            }
        });
        return future;
    }

    private Future<SQLConnection> createSomeDataIfNone(SQLConnection connection) {
        Future<SQLConnection> future = Future.future();
        connection.query("SELECT * FROM TransferTasks", select -> {
            if (select.failed()) {
                future.fail(select.cause());
            } else {
                if (select.result().getResults().isEmpty()) {
                    TransferTask transferTask1= new TransferTask("agave://sftp//etc/hosts", "agave://sftp//tmp/hosts1", "testuser", null, null);
                    TransferTask transferTask2 = new TransferTask("agave://sftp//etc/hosts", "agave://sftp//tmp/hosts2", "testuser", null, null);
                    TransferTask transferTask3 = new TransferTask("agave://sftp//etc/hosts", "agave://sftp//tmp/hosts3", "testuser", null, null);
                    Future<TransferTask> insertion1 = insert(connection, transferTask1, false);
                    Future<TransferTask> insertion2 = insert(connection, transferTask2, false);
                    Future<TransferTask> insertion3 = insert(connection, transferTask3, false);
                    CompositeFuture.all(insertion1, insertion2)
                            .setHandler(r -> future.handle(r.map(connection)));
                } else {
                    future.complete(connection);
                }
            }
        });
        return future;
    }

    // ---- HTTP Actions ----

    private void getAll(RoutingContext rc) {
        if ( ! authenticate(rc.request()) ) {

        }

        connect()
                .compose(this::query)
                .setHandler(ok(rc));
    }

    private void addOne(RoutingContext rc) {
        TransferTask transferTask = rc.getBodyAsJson().mapTo(TransferTask.class);
        connect()
                .compose(connection -> insert(connection, transferTask, true))
                .setHandler(created(rc));
    }


    private void deleteOne(RoutingContext rc) {

        String id = rc.pathParam("id");
        connect()
                .compose(connection -> delete(connection, id))
                .setHandler(noContent(rc));
    }


    private void getOne(RoutingContext rc) {
        String id = rc.pathParam("id");
        connect()
                .compose(connection -> queryOne(connection, id))
                .setHandler(ok(rc));
    }

    private void updateOne(RoutingContext rc) {
        String id = rc.request().getParam("id");
        TransferTask transferTask = rc.getBodyAsJson().mapTo(TransferTask.class);
        connect()
                .compose(connection -> update(connection, id, transferTask))
                .setHandler(noContent(rc));
    }

    // --------- Getters and Setters --------------

    public JWTAuth getAuthProvider() {
        if (authProvider == null) {
            JWTAuthOptions jwtAuthOptions = new JWTAuthOptions()
                    .addPubSecKey(new PubSecKeyOptions()
                            .setAlgorithm("HS256")
                            .setPublicKey(config.getString("conf/publickey")));

            authProvider = JWTAuth.create(vertx, jwtAuthOptions);
        }

        return authProvider;
    }

    public void setAuthProvider(JWTAuth authProvider) {
        this.authProvider = authProvider;
    }

    public void setConfig(JsonObject config) {
        this.config = config;
    }
}
